services:
  server:
    container_name: slm-llama-cpp-poc
    # image: vvasylkovskyi1/vvasylkovskyi-slm-poc:c60c211061a93c8b70935fa3576a297eaa5ba1d1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
