services:
  server:
    container_name: slm-llama-cpp-poc
    image: ${DOCKER_IMAGE:-slm-llama-cpp-poc:local}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALLOY_HOST=host.docker.internal
      - PHOENIX_COLLECTOR_ENDPOINT=http://host.docker.internal:4317
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "10000:10000"
